---

# reload systemd
- name: systemctl daemon-reload
  systemd:
    daemon_reload: true
  changed_when: false
  ignore_errors: true

# Restart confluence service
- name: confluence restart
  service:
    name: "confluence"
    state: "restarted"
  loop: "{{ ansible_play_hosts }}"
  delegate_to: "{{ item }}"
  run_once: true
  changed_when: false
  ignore_errors: true
